# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b73c3318007e981dd9915f13c01acdd65aa0d176a21c12ce0be8cecd1405bbfb295aaaf3289ac4cd68b5c59e7b8a3616352e61ef861b941b03a2b4df1f718fd

test:
  secret_key_base: 231e845f9fafe7512b34d19c78e785a857416862eb0c14be3af8fa57f58d310c1c49d18a9516b16c018ecd056043e4f4017e6fcc434e91de5170127fe8e63ed4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
